spring.application.name=backend

spring.mongodb.uri=mongodb+srv://socialmedia:socialPassword@cloud-social-media.itxzxuf.mongodb.net/cloud_social_media?retryWrites=true&w=majority&appName=cloud-social-media

server.port=8081

cloudinary.cloud-name=vsghifuq
cloudinary.api-key=793272512682122
cloudinary.api-secret=GOJNSmDkL4v7bYLHpERftTAKPC0

#
#spring.security.user.name=user
#spring.security.user.password=user@123